#!/home/rjonnal/miniconda2/bin/python

from octopod import Model
from octopod.VisualizationTools import ProjectionMaker,Viewer3D
import sys
from optparse import OptionParser

parser = OptionParser()


mode_options = {}
mode_options['volume'] = 'show 3D raycasting projection of volume'
mode_options['enface'] = 'show selectable en face projection of volume'
mode_options['label'] = 'label axial scattering model'

mode_string = ''
for key in mode_options.keys():
    mode_string = mode_string + '%s: %s; '%(key,mode_options[key])

parser.add_option("-m","--mode",dest="mode",type="string",default="enface",help=mode_string)
parser.add_option("-v","--vidx",dest="vidx",type="int",default=0,help="index of the volume to show")
parser.add_option("-d","--depth",dest="depth",type="int",default=256,help="thickness of the volume to show")

(options, args) = parser.parse_args()
print options
mode = options.mode
vidx = options.vidx
depth = options.depth
fn = sys.argv[-1]


if mode.lower()=='volume':
    v3d = Viewer3D(fn,vidx=vidx,depth=depth)
elif mode.lower()=='enface':
    pm = ProjectionMaker(fn,vidx=vidx)
    pm.project()
elif mode.lower()=='label':
    m = Model(fn,True)
    m.clear_labels()
    m.click_label()

