        avol = np.abs(self.h5['processed_data'])
        lrp = np.mean(np.mean(np.mean(avol,axis=3),axis=1),axis=0)
        noise_region = avol[:][:][:][:10]
        plt.hist(noise_region.ravel(),100)
        noise_rms = np.std(noise_region.ravel())
        plt.figure()
        plt.plot(lrp)
        plt.axhline(noise_rms)
        plt.show()
        sys.exit()
